doctor/appbase/urls.py
from django.contrib import admin
from django.urls import path
from appbase.views import CreatePacienteView, UpdatePacienteView,ListPacienteView
from django.conf import settings
app_name = "base"
urlpatterns = [
    path('paciente/', ListPacienteView.as_view(), name='paciente'),
    path('paciente_registro/', CreatePacienteView.as_view(), name='pac_r'),
    path('paciente_actualizar/<int:pk>/', UpdatePacienteView.as_view(), name='act_paciente'),
]

doctor/appconsulta/urls.py
from django.contrib import admin
from django.urls import path
from appconsulta.views import  DoctorView, HistoriaView, CitaView, AgendaView, \
    HorarioView, RecetaView, AntecedentesView, UsuarioView
from django.conf import settings
app_name = "consulta"
urlpatterns = [
    path('doctor/', DoctorView.as_view(), name='doctor'),
    path('historia-clinica/', HistoriaView.as_view(), name='historia'),
    path('nueva-cita/', CitaView.as_view(), name='cita'),
    path('agenda/', AgendaView.as_view(), name='agenda'),
    path('horario-atencion/', HorarioView.as_view(), name='horario'),
    path('receta-paciente/', RecetaView.as_view(), name='receta'),
    path('antecedentes/', AntecedentesView.as_view(), name='antecedentes'),
    path('usuarios/', UsuarioView.as_view(), name='usuario'),
]

doctor/doctor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from appbase.views import InicioView, InicioLoginView, RegistroLoginView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InicioLoginView.as_view(),name='login'),
    path('registrar', RegistroLoginView.as_view(),name='registrar'),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('consulta/', include('appconsulta.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

doctor/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medical</title>
    {% load static%}
    <!-- datepicker-->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">

    {% block headcss %}

    {% endblock %}

</head>

<body>
    <header>
        {% block header %}

        {% endblock %}
    </header>
    <main>
        {% block main %}
        {% endblock %}
       
    </main>
    <footer class="bg-dark">
        <div class="container text-center text-md-left">
            <div class="row">
              <div class="col-md-3 mx-auto">
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4 text-white">Integrantes</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Tamara Pazmiño</a>
                  </li>
                  <li>
                    <a href="#!">Tahiri Garcia</a>
                  </li>
                  <li>
                    <a href="#!">Gabriela Loyola</a>
                  </li>
                  <li>
                    <a href="#!">Edison Bueno</a>
                  </li>
                </ul>
              </div>
              <hr class="clearfix w-100 d-md-none">
              <div class="col-md-3 mx-auto">
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4 text-white">Tecnologias Utilizadas</h5>  
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Python</a>
                  </li>
                  <li>
                    <a href="#!">Framework Django</a>
                  </li>
                  <li>
                    <a href="#!">Bootstrap 4</a>
                  </li>
                </ul>
              </div>
              <hr class="clearfix w-100 d-md-none">
              <div class="col-md-3 mx-auto">
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4 text-white">Información</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#">tpazminon@unemi.edu.ec</a>
                    <a href="#!">tgarcial2@unemi.edu.ec</a>
                    <a href="#!">gloyolas2@unemi.edu.ec</a>
                    <a href="#!">ebuenop@unemi.edu.ec</a>
                  </li>
                </ul>
              </div>
              </div>
            </div>
          </div>
          <div class="footer-copyright text-center py-3"><strong>© 2020 Copyright:</strong>
          </div>
    </footer>

    {% block frmodal %}

    {% endblock %}



    <!-- En el orden jQuery, Popper.js y Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>


    {% block js %}

    {% endblock %}

    {% block jscript %}

    {% endblock %}
</body>

</html>

doctor/templates/header.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <span class="text-light font-weight-bold"><img src="{% static 'imagenes/logo.png' %}"
                width="18px">edical</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active ">
                <a class="btn btn-primary " data-toggle="tooltip" data-placement="bottom" title=""
                    data-original-title="Menu Principal" href="{% url 'inicio' %}"> Inicio<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class=" btn btn-flat-info btn-small" data-toggle="tooltip" data-placement="top" title=""
                    data-original-title="Administracion de Entidades" href="/admin"><span
                        class="text-white">Administracion</span></a>
            </li>
            <li class="nav-item">
                <a class="btn btn-flat-info btn-small" data-toggle="tooltip" data-placement="bottom" title=""
                    data-original-title="Atencion de Pacientes" href="{% url 'base:paciente' %}"><span class="text-white">
                        Atencion</span></a>
            </li>


            <li class="nav-item">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="bottom" title=""
                        data-original-title="Configurar Datos de Doctores">Agenda</button>
                    <div class="btn-group show" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
                        <div class="dropdown-menu " aria-labelledby="btnGroupDrop1"
                            style="position: absolute; transform: translate3d(0px, 34px, 0px); top: 0px; left: 0px; will-change: transform;"
                            x-placement="bottom-start">
                            <a class="dropdown-item" href="{% url 'consulta:receta' %}">Recetas</a>
                            <a class="dropdown-item" href="{% url 'consulta:antecedentes' %}">Antecedentes</a>
                            <a class="dropdown-item" href="{% url 'consulta:horario' %}">Horario</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item">
                <a id="fec" class="nav-link" href="#"></a>
            </li>
            <li>
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown ">
                    <div role="group">
                        <a class="nav-link active dropdown-toggle" id="senc"  data-toggle="dropdown" data-placement="right"
                        aria-haspopup="true" aria-expanded="true" href="#"  role="button">
                            <span class="inner">
                                <img class="rounded" id="imgusuario" src="{% static 'imagenes/login-user.png' %}" width="20px">
                            </span>
                            Tamara
                        </a>
                        <div class="dropdown-menu " aria-labelledby="senc"
                            style="position: absolute; transform: translate3d(0px, 34px, 0px); top: 0px; left: 0px; will-change: transform;"
                            x-placement="bottom-start">
                            <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="{% url 'login' %}">Cerrar Sessión</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>
<!-- menu vertical Sidenav -->
{% block jscript %}
<script>
    let fecha = new Date()
    let dia = fecha.getDate()
    let mes = fecha.getMonth()+1
    if (dia<10){
        dia='0'+dia
    }
    if (mes<10) {
        mes = '0'+mes
    }
    document.getElementById('fec').innerHTML=dia+"-"+mes +"-"+fecha.getFullYear()
</script>
{% endblock %}