doctor/appbase/urls.py
from django.contrib import admin
from django.urls import path
from appbase.views import CreatePacienteView, UpdatePacienteView,ListPacienteView
from django.conf import settings
app_name = "base"
urlpatterns = [
    path('paciente/', ListPacienteView.as_view(), name='paciente'),
    path('paciente_registro/', CreatePacienteView.as_view(), name='pac_r'),
    path('paciente_actualizar/<int:pk>/', UpdatePacienteView.as_view(), name='act_paciente'),
]

doctor/doctor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from appbase.views import InicioView, InicioLoginView, RegistroLoginView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InicioLoginView.as_view(),name='login'),
    path('registrar', RegistroLoginView.as_view(),name='registrar'),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('consulta/', include('appconsulta.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

doctor/appbase/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date


class Provincia(models.Model):
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Ciudad(models.Model):
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    descripcion = models.CharField(verbose_name='Descripcion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Profesion(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Profesion'
        verbose_name_plural = 'Profesiones'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Titulo(models.Model):
    descripcion = models.CharField(
        verbose_name='Descripcion', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Titulo'
        verbose_name_plural = 'Titulos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Persona(models.Model):
    tipo_sexo = (('N', 'Ninguno'), ('M', 'Masculino'), ('F', 'Femenino'))
    estado_civil = (('S', 'Soltero'), ('C', 'Casado'),
                    ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union'))
    cedula = models.CharField('Cedula', max_length=13, unique=True)
    nombre = models.CharField(max_length=100, verbose_name='Nombres')
    apellido = models.CharField(max_length=100, verbose_name='Apellidos')
    nacimiento = models.DateField('Fecha Nacimiento', blank=True, null=True)
    sexo = models.CharField('sexo', choices=tipo_sexo,
                            default='N', max_length=1)
    civil = models.CharField(
        'Estado civil', choices=estado_civil, default='S', max_length=1)
    profesion = models.ManyToManyField(Profesion)
    titulo = models.ManyToManyField(Titulo)
    provincia = models.ForeignKey(
        Provincia, on_delete=models.PROTECT, blank=True, null=True)
    ciudad = models.ForeignKey(
        Ciudad, on_delete=models.PROTECT, blank=True, null=True)
    direccion = models.CharField(
        'Direccion', max_length=100, blank=True, null=True)
    telefono = models.CharField(
        'Telefono', max_length=100, blank=True, null=True)
    email = models.EmailField('Correo', max_length=100, blank=True, null=True)
    foto = models.ImageField('Foto', upload_to='fotos/', blank=True, null=True)

    class Meta:
        abstract = True

    def get_foto(self):
        try:
            return str(self.foto.url)
        except:
            pass
        return None


class Sangre(models.Model):
    tipo = models.CharField('Tipo de Sangre', max_length=20, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Tipo de Sangre'
        verbose_name_plural = 'Tipos de Sangre'

    def __str__(self):
        return '{}'.format(self.tipo)


class Horario(models.Model):
    DIA_SEMANA = ((0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'),
                  (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'))
    dia = models.IntegerField('Dia', choices=DIA_SEMANA, default=1)
    desde = models.TimeField('Desde', blank=True, null=True, default='00:00')
    hasta = models.TimeField('Hasta', blank=True, null=True, default='00:00')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'
        ordering = ['dia']

    def __str__(self):
        return '{}'.format(self.dia)

    def dia_semana(self):
        return self.DIA_SEMANA[self.dia][1]


class Paciente(Persona):
    sangre = models.ForeignKey(
        Sangre, on_delete=models.PROTECT, blank=True, null=True)
    hijos = models.IntegerField('No.hijos', default=0)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return '{}'.format(self.nombre)


class Doctor(Persona):
    consultorio = models.CharField('Nombre de Consultorio', max_length=100)
    lugar = models.CharField('Direccion de Consultorio', max_length=100)
    logo = models.ImageField('Logo', upload_to='logos/', blank=True, null=True)
    horario = models.ManyToManyField(Horario)
    registro = models.CharField('Registro Medico', max_length=50)
    duracion = models.IntegerField('Duracion de Consulta', default=30)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctores'

    def __str__(self):
        return '{}'.format(self.nombre)


class Agenda(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    fecha = models.DateField(
        'Fecha de Agenda', blank=True, null=True, default=date.today())
    hora = models.TimeField('Hora', default=datetime.now().time())
    motivo = models.CharField('Motivo de Consulta', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'

    def __str__(self):
        return '{}'.format(self.fecha)


class GrupoAntecedente(models.Model):
    descripcion = models.CharField(
        'Grupo de Antecedente', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Grupo de Antecedente'
        verbose_name_plural = 'Grupo de Antecedentes'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Antecedente(models.Model):
    grupoAntecedente = models.ForeignKey(
        GrupoAntecedente, on_delete=models.PROTECT)
    descripcion = models.CharField('Antecedente', max_length=100, unique=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Antecedente'
        verbose_name_plural = 'Antecedentes'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Medicamento(models.Model):
    descripcion = models.CharField('Medicamento', max_length=100)
    foto = models.ImageField(
        'Foto', upload_to='medicamentos/', blank=True, null=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Frecuencia(models.Model):
    descripcion = models.CharField('Frecuencia', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Frecuencia'
        verbose_name_plural = 'Frecuencias'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Dosis(models.Model):
    descripcion = models.CharField('Dosis', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Dosis'
        verbose_name_plural = 'Dosis'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Duracion(models.Model):
    descripcion = models.CharField('Duracion', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Duracion'
        verbose_name_plural = 'Frecuencias'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Sintoma(models.Model):
    descripcion = models.CharField('Sintoma', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Sintoma'
        verbose_name_plural = 'Sintomas'

    def __str__(self):
        return '{}'.format(self.descripcion)


class Diagnostico(models.Model):
    codigo = models.CharField('Codigo', max_length=100)
    descripcion = models.CharField('Diagnostico', max_length=100)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Diagnostico'
        verbose_name_plural = 'Diagnosticos'

    def __str__(self):
        return '{}'.format(self.descripcion)


class SignoVital(models.Model):
    descripcion = models.CharField('Signo', max_length=100)
    rango1 = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    rango2 = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    medida = models.CharField('Medida', max_length=10)
    imagen = models.ImageField(
        'imagen', upload_to='signovital/', blank=True, null=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Signo Vital'
        verbose_name_plural = 'Signo Vitales'

    def __str__(self):
        return '{}'.format(self.descripcion)


class EstudioGabinete(models.Model):
    descripcion = models.TextField('Estudio de gabinete')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Estudio de Gabinete'
        verbose_name_plural = 'Estudio de Gabinete'

    def __str__(self):
        return '{}'.format(self.descripcion)


class AudiUsuarioTabla(models.Model):
    TIPOS_ACCIONES = (
        ('A', 'A'),  # Adicion
        ('M', 'M'),  # Modificacion
        ('E', 'E'),  # Eliminacion
    )
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    tabla = models.CharField(max_length=100, verbose_name='Tabla')
    registroid = models.IntegerField(verbose_name='Registro Id')
    accion = models.CharField(choices=TIPOS_ACCIONES,
                              max_length=1, verbose_name='Accion')
    fecha = models.DateField(verbose_name='Fecha')
    hora = models.TimeField(verbose_name='Hora')

doctor/appbase/forms.py
from django import forms
from .models import Paciente

class PacienteForm(forms.ModelForm):
    
        class Meta:
            model = Paciente
            fields = '__all__'

        def __init__(self, *args, **kwargs):
            super(PacienteForm, self).__init__(*args,**kwargs)
            self.fields['foto'].widget.attrs['class'] = ' btn btn-warning btn-sm'
            self.fields['cedula'].widget.attrs['class'] = 'form-control'
            self.fields['cedula'].widget.attrs['placeholder'] = 'cedula'
            self.fields['nombre'].widget.attrs['class'] = 'form-control'
            self.fields['nombre'].widget.attrs['placeholder'] = 'Ingrese sus nombres'
            self.fields['apellido'].widget.attrs['class'] = 'form-control'
            self.fields['apellido'].widget.attrs['placeholder'] = 'Ingrese sus apellidos'
            self.fields['nacimiento'].widget.attrs['class']='form-control'
            self.fields['sexo'].widget.attrs['class']='form-control'
            self.fields['civil'].widget.attrs['class']='form-control'
            self.fields['profesion'].widget.attrs['class']='form-control'
            self.fields['titulo'].widget.attrs['class']='form-control'
            self.fields['provincia'].widget.attrs['class']='form-control'
            self.fields['ciudad'].widget.attrs['class']='form-control'
            self.fields['telefono'].widget.attrs['class']='form-control'
            self.fields['direccion'].widget.attrs['class']='form-control'
            self.fields['email'].widget.attrs['placeholder']='@example.com'
            self.fields['email'].widget.attrs['class']='form-control'
            self.fields['sangre'].widget.attrs['class']='form-control'
            self.fields['hijos'].widget.attrs['class']='form-control'
            
            
           

doctor/appbase/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Paciente
from .forms import PacienteForm


class InicioView(TemplateView):
    template_name = "index.html"

class InicioLoginView(TemplateView):
    template_name = "inicio-login/login.html"

class RegistroLoginView(TemplateView):
    template_name = "inicio-login/registrar.html"

class ListPacienteView(ListView):
    model = Paciente
    template_name = "appbase/paciente/paciente.html"
    context_object_name = "pacientes"

class CreatePacienteView(CreateView):
    model = Paciente
    form_class = PacienteForm
    template_name = "appbase/paciente/registro.html"
    success_url = reverse_lazy('base:paciente')
    form_valid_message = 'Datos Guardados'
    form_invalid_message = 'Error'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['POST'] = True
        return context

class UpdatePacienteView(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = "appbase/paciente/registro.html"
    success_url = reverse_lazy('base:paciente')

doctor/templates/appbase/paciente/paciente.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}


<div class="container-fluid" id="inicio">
    <div class="row">
      
        <div class="col-s12 col-md-12">
            <div class="card-header bg-light text-dark ">
                <div class="row">
                    <div class="col-md-8">
                        <h3 id="titulo" class="font-weight-bold" >CONSULTA DE PACIENTES <span class="material-icons">
                            supervisor_account
                        </span></h3>
                    </div>
                    <div class="col-md-4 ">
                        <a href="{% url 'base:pac_r' %}" class="btn btn-primary float-right">Nuevo Registro</a>
                    </div>
    
                </div>
            </div>
            <table class="table table-hover table-striped mt-3">

                <thead class="bg-info text-dark">

                    <tr>
                        <th scope="col">Foto</th>
                        <th scope="col">Paciente</th>
                        <th scope="col">Género</th>
                        <th scope="col">Dirección</th>
                        <th scope="col">Email</th>
                        <th scope="col">Tipo de Sangre</th>
                        <th scope="col">Ciudad</th>
                        <th scope="col">Historia Clínica</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th colspan="8">
                            <input type="text" class="form-control" placeholder="buscar">
                        </th>

                    </tr>
                   {% for paciente in pacientes %}
                        <tr>
                            {% if paciente.foto %}
                            <td><img src="{{paciente.foto.url}}" class="img-thumbnail rounded-circle" width="40px">
                            </td>
                            {% else %}
                            <td><img src="{% static 'imagenes/sinfoto.png' %}"class="img-thumbnail rounded-circle" width="40px">
                            </td>
                            {% endif %}
                            <td>{{paciente.nombre}} {{paciente.apellido}}</td>
                          
                                {% if paciente.sexo == 'M' %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-success">Masculino</span>
                                </td>
                                {% else %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-danger">Femenino</span>
                                </td>
                                {% endif %}
                          
                            <td>{{paciente.direccion}}</td>
                            <td>{{paciente.email}}</td>
                            <td><span
                                class="badge badge-pill badge-success">{{paciente.sangre}}</span></td>
                            <td>{{paciente.ciudad}}</td>
                            <td><a href="#" class="badge badge-pill badge-warning">ver historia</a></td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                    <div class="btn-group" role="group">
                                        <button id="btnGroupDrop{{paciente.id}}" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Accion</button>
                                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop{{paciente.id}}">
                                            <a class="dropdown-item" href="{% url 'base:act_paciente' paciente.id %}">Editar</a>
                                            <a class="dropdown-item" href="#">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% empty %}
                      <tr> <td><h3 class="text-danger">¡No existen registros...!</h3></td></tr>
                       
                   {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

doctor/templates/appbase/paciente/registro.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}


<div class="container" id="inicio">
    <div class="row">
        <div class="card col-s12 col-md-12">
            <form class=" form-group" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>

                    <legend> <span class="material-icons">
                            supervisor_account
                        </span> Registro de Pacientes</legend>
                        <div class="card-body">
                            <div id= "conten-vista" class="col form-group">
                            {% if POST %}
                            <img width="20%" height="50%" class="img-responsive" src="{% static 'imagenes/sinfoto.jpg' %}" alt="perfil">
                           {% else %}
                           <img width="20%" height="50%" class="img-responsive" src="{{form.instance.foto.url}}" alt="perfil">
                           {% endif %}
                            </div>
                          {{form.foto}}
                        </div>
                        {% if form.errors %}
                        <div class="col-md-8 alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                         <strong>{{form.errors}}</strong>
                        </div>
                        {% endif %}
                    <div class="row">
                        <div class="col form-group">
                            <label>Nombres:</label>
                             {{form.nombre}}
                        </div>
                        <div class="col form-group">
                            <label>Apellidos:</label>
                           {{form.apellido}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Cédula:</label>
                          {{form.cedula}}
                        </div>
                        <div class="col form-group">
                            <label>Estado Civil:</label>
                          {{form.civil}}
                        </div>
                        <div class="col form-group">
                            <label>Sexo:</label>
                            {{form.sexo}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Profesión:</label>
                          {{form.profesion}}
                        </div>
                        <div class="col form-group">
                            <label>Titulo:</label>
                            {{form.titulo}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Fecha Nacimiento:</label>
                                {{form.nacimiento}}
                        </div>
                        <div class="col form-group">
                            <label>Telefono:</label>
                           {{form.telefono}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Provincia:</label>
                                {{form.provincia}}
                        </div>
                        <div class="col form-group">
                            <label>Ciudad:</label>
                           {{form.ciudad}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Dirección:</label>
                         {{form.direccion}}
                        </div>
                        <div class="col form-group">
                            <label>Correo Electrónico:</label>
                            {{form.email}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Tipo de Sangre:</label>
                         {{form.sangre}}
                        </div>
                        <div class="col form-group">
                            <label>Hijos:</label>
                           {{form.hijos}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col form-group">
                            <label>Estado:</label>
                         {{form.estado}}
                    </div>
                </fieldset>
                <div class="form-group form-inline">
                    <label class="col-sm-6 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary btn-sm"> Registrar</button>
                        <a href="{% url 'base:paciente' %}" class="btn btn-danger btn-sm">Cancelar</a>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function(){
    function vista_previa(entrada) {
      if (entrada.files && entrada.files[0]) {
        let fr = new FileReader();
        fr.onload = function(evt){
          $("#conten-vista").html("<img  width=200px height=auto src="+evt.target.result+" />");
        }
        fr.readAsDataURL(entrada.files[0]);
      }
    }
        $("#id_foto").change(function(){
            let filename = $("#id_foto").val();
            if (filename=='') {
                $("#conten-vista").html("<img  width=200px height=auto src='{% static 'imagenes/sinfoto.jpg' %}' />");
            }else{
                vista_previa(this);
            }
        });
    
    });
    </script>
{% endblock %}